server:
  port: 9090
  # HTTPS certification
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 328626
    keyStoreType: PKCS12
    keyAlias: tomcat
  
#mysql database setting  
jdbc:
  driver: com.mysql.jdbc.Driver  
  url: jdbc:mysql://localhost:3306/WAppDatabase?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull  
  username: root  
  password: 328626  
  #connection pool settings  
  pool:
    maxIdle: 10  
    maxActive: 40  